# reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
osx_image: xcode8.0
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
matrix:
  include:
   # - osx_image: xcode8
   #   env: FASTLANE_LANE=code_coverage FASTLANE_ENV=default
   # - osx_image: xcode8
    #  env: FASTLANE_ENV=ios10_xcode8
    #- osx_image: xcode7.3
    #  env: FASTLANE_ENV=ios93_xcode73
    #- osx_image: xcode7.3
    #  env: FASTLANE_ENV=ios81_xcode73
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
