source 'https://github.com/CocoaPods/Specs.git'

target 'LJPhotoBrowser' do
  pod "DACircularProgress"
  pod 'SDWebImage/GIF'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'PSTCollectionView'
  pod 'SDWebImage'
  pod 'SVProgressHUD'

end
