source 'https://github.com/CocoaPods/Specs.git'

target 'LJPhotoBrowser' do
    pod 'SDWebImage/GIF'
    pod 'Masonry',                '~> 1.0.2'
    pod 'MBProgressHUD’,          '~> 1.0.0'
    pod 'DACircularProgress',     '~> 2.3.1'
    pod 'SDWebImage’,             '~> 4.0.0'
    pod 'SVProgressHUD',          '~> 2.1.2'
    pod 'PSTCollectionView',      '~> 1.2.3'

end
